# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-23 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bind_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.HostGroup', verbose_name='主机组'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bind_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Host', verbose_name='主机'),
        ),
    ]
