# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-23 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20180223_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bind_group',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bind_group',
            field=models.ManyToManyField(blank=True, null=True, to='repository.HostGroup', verbose_name='主机组'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bind_host',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bind_host',
            field=models.ManyToManyField(blank=True, null=True, to='repository.Host', verbose_name='主机'),
        ),
    ]
