# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-28 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20180228_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BindHosts',
            new_name='BindUserHosts',
        ),
    ]
