# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20180228_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binduserhosts',
            options={'verbose_name': '主机绑定主机用户', 'verbose_name_plural': '主机绑定主机用户'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bind_host',
            field=models.ManyToManyField(blank=True, to='repository.Host', verbose_name='主机'),
        ),
    ]
