# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-01 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20180228_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='hosts',
            field=models.ManyToManyField(to='repository.BindUserHosts', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bind_host',
            field=models.ManyToManyField(blank=True, to='repository.BindUserHosts', verbose_name='主机'),
        ),
    ]
