# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Sessions',
        ),
    ]
