# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-08 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_task_tasklogdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklogdetail',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklogdetail',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
