# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-08 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20180308_0914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks',
        ),
    ]
