# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20180308_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='一级菜单')),
            ],
            options={
                'verbose_name': '一级菜单',
                'verbose_name_plural': '一级菜单',
            },
        ),
        migrations.CreateModel(
            name='MenuTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='二级菜单')),
                ('url_type', models.PositiveSmallIntegerField(choices=[(0, '相对路径'), (1, '绝对路径')], default=0, verbose_name='路径类型')),
                ('url_path', models.CharField(max_length=128, verbose_name='路径地址')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用菜单')),
                ('menu_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.MenuOne', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '二级菜单',
                'verbose_name_plural': '二级菜单',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
            ],
            options={
                'verbose_name': '角色授权',
                'verbose_name_plural': '角色授权',
            },
        ),
        migrations.AlterModelOptions(
            name='tasklogdetail',
            options={'verbose_name': '操作任务详情', 'verbose_name_plural': '操作任务详情'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': '操作任务', 'verbose_name_plural': '操作任务'},
        ),
        migrations.AlterField(
            model_name='tasklogdetail',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='menuone',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Role', verbose_name='所属角色'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(to='repository.Role', verbose_name='所属角色'),
        ),
    ]
