# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20180321_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuone',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='menu_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.MenuOne', verbose_name='一级菜单'),
        ),
    ]
