# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_auto_20180321_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='menu_one',
        ),
        migrations.AddField(
            model_name='role',
            name='menu_one',
            field=models.ManyToManyField(blank=True, null=True, to='repository.MenuOne', verbose_name='一级菜单'),
        ),
    ]
